evaluation_homepage:
    path:     /
    defaults: { _controller: EvaluationBundle:Default:index }

publication_add:
    path:     /publication/ajout
    defaults: { _controller: EvaluationBundle:Publication:up }

publication_list:
    path:     /publication/list
    defaults: { _controller: EvaluationBundle:Publication:list }

evaluation_home_user:
    path:     /user/home
    defaults: { _controller: EvaluationBundle:Security:redirect }


publication_comment:
    path:     /commentaire/{id}
    defaults: { _controller: EvaluationBundle:Publication:commentPub }

commentaire_new:
    path:     /commentaire/new/{idPub}
    defaults: { _controller: EvaluationBundle:Commentaire:add }

publication_edit:
    path:     /publication/edit/{id}
    defaults: { _controller: EvaluationBundle:Publication:edit }

user_add:
    path:     /user/add
    defaults: { _controller: EvaluationBundle:Security:add }

publication_vote:
    path:     /publication/vote/{id}
    defaults: { _controller: EvaluationBundle:Vote:vote }

publication_listApi:
    path:     /publication/api/list
    defaults: { _controller: EvaluationBundle:Publication:all }

publication_voteApi:
    path:     /publication/api/vote/{id}/{idUser}
    defaults: { _controller: EvaluationBundle:Publication:voteApi }

publication_addApi:
    path:     /publication/api/new
    defaults: { _controller: EvaluationBundle:Publication:addApi }

vote_voteEfApi:
    path:     /vote/api/verifVot/{id}
    defaults: { _controller: EvaluationBundle:Vote:verifApi }

vote_listApi:
    path:     /vote/api/list
    defaults: { _controller: EvaluationBundle:Vote:all }

